### ISSUE TITLE
A knowledge base with label val does not exist

### ISSUE THREAD

**Issue by DavidLeoni** [opendatatrentino/OpenDataRise#155]
fix nlp pipeline bug in Schema alignment: ODHPipeline bug in implementation, does't pass the right knowledge base label to the POS Tagger

```
2016-01-05 16:22:17,125 ERROR [AbstractController] - A knowledge base with label val does not exist
it.unitn.disi.sweb.core.nlp.exceptions.NLPException: A knowledge base with label val does not exist
    at it.unitn.disi.sweb.core.nlp.repository.hibernate.NLPRepository.getKnowledgeBase(NLPRepository.java:343)
    at it.unitn.disi.sweb.core.nlp.repository.hibernate.NLPRepository.getVocabulary(NLPRepository.java:356)
    at it.unitn.disi.sweb.core.nlp.repository.hibernate.NLPRepository.isLemmaExists(NLPRepository.java:270)
    at it.unitn.disi.sweb.core.nlp.repository.lexicon.CombinedLexicon.isLemmaExists(CombinedLexicon.java:117)
    at it.unitn.disi.sweb.core.nlp.components.lemmatizers.Lemmatizer.lemmatize(Lemmatizer.java:189)
    at it.unitn.disi.sweb.core.nlp.components.lemmatizers.Lemmatizer.lemmatize(Lemmatizer.java:157)
    at it.unitn.disi.sweb.core.nlp.components.lemmatizers.Lemmatizer.lemmatize(Lemmatizer.java:148)
    at it.unitn.disi.sweb.core.nlp.components.postaggers.ODHPOSTagger.process(ODHPOSTagger.java:110)
    at it.unitn.disi.sweb.core.nlp.components.postaggers.ODHPOSTagger.process(ODHPOSTagger.java:33)
    at it.unitn.disi.sweb.core.nlp.components.AbstractModelBasedComponent.process(AbstractModelBasedComponent.java:116)
    at it.unitn.disi.sweb.core.nlp.components.AbstractComponent.run(AbstractComponent.java:120)
    at it.unitn.disi.sweb.core.nlp.components.AbstractComponent.run(AbstractComponent.java:26)
    at it.unitn.disi.sweb.core.nlp.pipelines.AbstractPipeline.runPipeline(AbstractPipeline.java:105)
    at it.unitn.disi.sweb.core.nlp.pipelines.AbstractPipeline.runPipeline(AbstractPipeline.java:56)



```

**Comment by DavidLeoni** [comment]
Fixed in branch-0.3  .  Could have been a combination of disi client hardcoded ids (see https://github.com/opendatatrentino/disi-open-data-client/issues/25)  and server side nlp problems.
