### ISSUE TITLE
Jackson can't deserialize ProvenanceColumnRef into  ProvenanceRef

### ISSUE THREAD

**Issue by DavidLeoni** [opendatatrentino/OpenDataRise#85]
Mysterious bug. With jsons in test works, with json from the browser doesn't. 
Will deserialize manually for now.

```
11:28:07.347 [                   Odrext] schema = {"targetEntityTypeUrl":"ukc:et/facility","mappings":[{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":0},"targetAttributeUrl":"ukc:ad/name"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":1},"targetAttributeUrl":"ukc:ad/opening-time"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":1},"targetAttributeUrl":"ukc:ad/closing-time"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":2},"targetAttributeUrl":"ukc:ad/class"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":3},"targetAttributeUrl":"ukc:ad/class"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":4},"targetAttributeUrl":"ukc:ad/latitude"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":5},"targetAttributeUrl":"ukc:ad/longitude"}]} (1ms)
11:28:07.347 [                   Odrext] Loading schema: {"targetEntityTypeUrl":"ukc:et/facility","mappings":[{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":0},"targetAttributeUrl":"ukc:ad/name"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":1},"targetAttributeUrl":"ukc:ad/opening-time"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":1},"targetAttributeUrl":"ukc:ad/closing-time"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":2},"targetAttributeUrl":"ukc:ad/class"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":3},"targetAttributeUrl":"ukc:ad/class"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":4},"targetAttributeUrl":"ukc:ad/latitude"},{"sourceRef":{"className":"eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef","index":5},"targetAttributeUrl":"ukc:ad/longitude"}]} (0ms)
11:28:07.359 [                   refine] Had problems loading schema
  rethrowed exception message: Invalid type id 'eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef' (for id type 'Id.class'): Class eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef is not assignable to eu.trentorise.opendata.opendatarise.provenance.ProvenanceRef (through reference chain: eu.trentorise.opendata.opendatarise.model.Schema["mappings"]->eu.trentorise.opendata.opendatarise.model.Mapping["sourceRef"])
  rethrowed exception cause:   java.lang.IllegalArgumentException: Invalid type id 'eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef' (for id type 'Id.class'): Class eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef is not assignable to eu.trentorise.opendata.opendatarise.provenance.ProvenanceRef (12ms)
11:28:07.359 [                  command] Exception caught (0ms)
com.google.refine.OdrException: Had problems loading schema
	at eu.trentorise.opendata.opendatarise.model.Schema.load(Schema.java:58)
	at eu.trentorise.opendata.opendatarise.commands.SetSchemaCommand.doPost(SetSchemaCommand.java:42)
	at com.google.refine.RefineServlet.service(RefineServlet.java:430)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at org.mortbay.servlet.UserAgentFilter.doFilter(UserAgentFilter.java:81)
	at org.mortbay.servlet.GzipFilter.doFilter(GzipFilter.java:132)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:938)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:755)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:722)
Caused by: org.codehaus.jackson.map.JsonMappingException: Invalid type id 'eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef' (for id type 'Id.class'): Class eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef is not assignable to eu.trentorise.opendata.opendatarise.provenance.ProvenanceRef (through reference chain: eu.trentorise.opendata.opendatarise.model.Schema["mappings"]->eu.trentorise.opendata.opendatarise.model.Mapping["sourceRef"])
	at org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:218)
	at org.codehaus.jackson.map.JsonMappingException.wrapWithPath(JsonMappingException.java:183)
	at org.codehaus.jackson.map.deser.BeanDeserializer.wrapAndThrow(BeanDeserializer.java:1472)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:699)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:217)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:194)
	at org.codehaus.jackson.map.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:299)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$FieldProperty.deserializeAndSet(SettableBeanProperty.java:579)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
	at org.codehaus.jackson.map.ObjectReader._bindAndClose(ObjectReader.java:768)
	at org.codehaus.jackson.map.ObjectReader.readValue(ObjectReader.java:460)
	at eu.trentorise.opendata.opendatarise.model.Schema.load(Schema.java:52)
	... 24 more
Caused by: java.lang.IllegalArgumentException: Invalid type id 'eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef' (for id type 'Id.class'): Class eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef is not assignable to eu.trentorise.opendata.opendatarise.provenance.ProvenanceRef
	at org.codehaus.jackson.map.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:59)
	at org.codehaus.jackson.map.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:113)
	at org.codehaus.jackson.map.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:82)
	at org.codehaus.jackson.map.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:52)
	at org.codehaus.jackson.map.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:297)
	at org.codehaus.jackson.map.deser.SettableBeanProperty$FieldProperty.deserializeAndSet(SettableBeanProperty.java:579)
	at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:697)
	... 35 more
Caused by: java.lang.IllegalArgumentException: Class eu.trentorise.opendata.opendatarise.provenance.ProvenanceColumnRef is not assignable to eu.trentorise.opendata.opendatarise.provenance.ProvenanceRef
	at org.codehaus.jackson.type.JavaType._assertSubclass(JavaType.java:485)
	at org.codehaus.jackson.type.JavaType.narrowBy(JavaType.java:163)
	at org.codehaus.jackson.map.type.TypeFactory.constructSpecializedType(TypeFactory.java:337)
	at org.codehaus.jackson.map.jsontype.impl.ClassNameIdResolver.typeFromId(ClassNameIdResolver.java:55)
	... 41 more
```

**Comment by DavidLeoni** [comment]
We don't use butterfly to load classes anymore. Now all classes are loaded by same war classloader (which is not good for isolation but switching to OSGi is too cumbersome now...)
